### ISSUE TITLE
Broken DVDFab live update API

### ISSUE THREAD

**Issue by test3yayayangyang** [hyugogirubato/DVDFabExtendDownload#2]

**Comment by test3yayayangyang** [comment]
I'm sorry I didn't check it properly.

**Comment by TURBOKANTR** [comment]
I'm getting "[!] Exception: string indices must be integers"

**Comment by hyugogirubato** [comment]
DVDFab made some changes, I'll look soon when I have time

**Comment by hyugogirubato** [comment]
The errors have been corrected but the script no longer works live. Archived project
