### ISSUE TITLE
Program with error

### ISSUE THREAD

**Issue by agryo** [hyugogirubato/DVDFabExtendDownload#3]
I don't know if you need an update, but the program that was working is no longer working and displays the message below...

Traceback (most recent call last):
  File "D:\DVDFabExtendDownload\dvdfab.py", line 154, in <module>
    version, index = pick([v['version'] for v in versions], 'Version')
                           ~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by hyugogirubato** [comment]
The errors have been corrected but the script no longer works live. Archived project.
